name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Hadolint
      uses: reviewdog/action-hadolint@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-check
        exclude: /.devcontainer/*
        level: info

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build the Docker image python-docker-gcloud
      run: docker build containers/python-docker-gcloud/.devcontainer --file containers/python-docker-gcloud/.devcontainer/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image terraform-aws
      run: docker build containers/terraform-aws/.devcontainer --file containers/terraform-aws/.devcontainer/Dockerfile --tag my-image-name:$(date +%s)
